// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkAWF90wB-qvCi22QlWEwI3CVhodZ0xGQ',
    appId: '1:1056176794632:web:9324eda2dde955a8a375bd',
    messagingSenderId: '1056176794632',
    projectId: 'buildnotifier-e5c6e',
    authDomain: 'buildnotifier-e5c6e.firebaseapp.com',
    storageBucket: 'buildnotifier-e5c6e.appspot.com',
    measurementId: 'G-V77G6QNPJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARu6RiMB2KroBEXdA746n_jIyl0Bt82aQ',
    appId: '1:1056176794632:android:22832261346d8991a375bd',
    messagingSenderId: '1056176794632',
    projectId: 'buildnotifier-e5c6e',
    storageBucket: 'buildnotifier-e5c6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0YeQS5ygbjtGbYiIhDKwcTx_1CfM1Uk',
    appId: '1:1056176794632:ios:65f5517afbbf01bca375bd',
    messagingSenderId: '1056176794632',
    projectId: 'buildnotifier-e5c6e',
    storageBucket: 'buildnotifier-e5c6e.appspot.com',
    iosBundleId: 'com.example.buildnotifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0YeQS5ygbjtGbYiIhDKwcTx_1CfM1Uk',
    appId: '1:1056176794632:ios:65f5517afbbf01bca375bd',
    messagingSenderId: '1056176794632',
    projectId: 'buildnotifier-e5c6e',
    storageBucket: 'buildnotifier-e5c6e.appspot.com',
    iosBundleId: 'com.example.buildnotifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkAWF90wB-qvCi22QlWEwI3CVhodZ0xGQ',
    appId: '1:1056176794632:web:f652f5c184a78d9ba375bd',
    messagingSenderId: '1056176794632',
    projectId: 'buildnotifier-e5c6e',
    authDomain: 'buildnotifier-e5c6e.firebaseapp.com',
    storageBucket: 'buildnotifier-e5c6e.appspot.com',
    measurementId: 'G-V312C8X3YN',
  );
}
